name: Check PR
'on': pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd client && npm ci && npm run generate
      - run: cd functions && npm ci && npm run lint && npm run build
